### PR TITLE
Move to primer-css and generally poke around.

### PR DESCRIPTION
**Pull request by plcstevens**

### CODE REVIEW

**Comment by dwhenry** [comment]
Not sure I like the fact that all the primer files are in the actual application.  Could you not find a Gem to contain this??

What is the arguement for it over bootstrap?? why does it contain html pages inside a css directory??

**Comment by plcstevens** [comment]
A gem would hold these just the same way ... at least this is following the standard bower pattern ...

**Comment by dwhenry** [comment]
Hmm.. and why is this better than bootstrap?? as my concern is adding new tech when the we know other stuff that works just as well and then having too big a mix of technology..

If we want to use bower components then lets split the app into two -> rails and node, rather than mixing everything inside one app..

**Comment by plcstevens** [comment]
I feel like we should really commit to doing it in two parts. I also need to commit time to this, free this weekend?

**Comment by dwhenry** [comment]
I am happy to do two parts.. but then the loading data in the page to avoid requests to load it is no longer possible.. as it is no longer rendered for the rails app..

but you can do server side rendering if you move everything to node (no rails)

so compromise all the way down, pick a path and then wonder around it..

**Comment by plcstevens** [comment]
I don't think moving to node solves much that we can't do with Rails right now? Just moves us to another MVC ...

I feel like having the front-end application inside assets and vendor/assets isn't a deadly mix (Discourse does it for instance). Lets try sticking with this, and yes, that does mean using bower_components.

**Comment by dwhenry** [comment]
so back to the original question.. why use primer-css over more traditional bootstrap css.. what if anything is the advantage..

And yes should have some free time this weekend..

**Comment by plcstevens** [comment]
I am happy to go with bootstrap, had just felt this might be fun to play with a far smaller subset of CSS. 

Lets go with bootstrap-css, use bowerfile and happy happy happy!

I am away on Sunday, Saturday I might need to buy a suit but otherwise think I am looking free, but maybe just better to find our own free time thinking about it ... rather than coming to meet.

**Comment by dwhenry** [comment]
Right so starting to get the the answer I was looking for:

> felt this might be fun to play with a far smaller subset of CSS

So finally read the primer doc intro and yes it sounds like it could be fun to try.  

Next question.. Why does it need to be compiled using brower.. can't it just be added to the repo and have the stylesheets compile under scss as per a standard rails app?

**Comment by dwhenry** [comment]
whatever

**Pull request merged**
